apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    app: {{ include "dummy-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dummy-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dummy-app.name" . }}
    spec:
      containers:
        - name: dummy-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text=Hello from GCE LoadBalancer"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
